### PR TITLE
Fix RWKV6 Cache Problems

### PR DESCRIPTION
**Pull request by WorldEditors**
Problems:

When the weight to forgetting gate be surfficiently large (>20), backward gives gradient = NAN (forward is still OK)

Solutions:

Clip (might have the risk of zero gradient) 
Add soft bound (with soft sign), might impact the exisiting model

### CODE REVIEW

**Comment by yzhangcs** [comment]
@WorldEditors Hi, thank you for the contributions. Unfortunately, I won't be able to accept these commits as it seems that the new code is not compatible with our existing pretrained ckpts, and I'm afraid that the NaNs could stem from some out of boundary issues. I will be working on this recently.Please stay tuned!

**Comment by yzhangcs** [comment]
I really appreciate your work on fixing the cache bugs. Could you please create a separate PR for those fixes? 
Since it's a different subject from this PR, I'd be happy to accept it separately.

**Comment by WorldEditors** [comment]
> I really appreciate your work on fixing the cache bugs. Could you please create a separate PR for those fixes? Since it's a different subject from this PR, I'd be happy to accept it separately.

Remove the softsign bound

**Comment by yzhangcs** [comment]
Thank you for the contributions.

**Pull request merged**
